version: '2'

services:
  axonbank1:
    image: axonframework/axonbank
    depends_on:
      - db
    ports:
      - "8080:8080"
  axonbank2:
    image: axonframework/axonbank
    depends_on:
      - db
    ports:
      - "8081:8080"
  db:
    image: mysql:5.7.15
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=axonbank
  rabbitmq:
    build: docker/rabbitmq/
